# Igual que ppyoloe_r_crn_s_banknotes.yml pero evaluando sobre el split TEST.
#   python PaddleDetection/tools/eval.py -c configs/ppyoloe_r_crn_s_banknotes_evaltest.yml -o weights=output/model_final.pdparams
_BASE_: ['ppyoloe_r_crn_s_banknotes.yml']

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: annotations/test.json
    dataset_dir: dataset/banknotes_obb
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']
