"""Single entry point to the split assignment.

No other module computes which split a sample belongs to. Everything reads
from splits/vN/{train,valid,test}.txt, never from the directory tree, so the
split stays frozen even if the data directory changes.

Versions
--------
`splits/` is a container of immutable versions: `v1`, `v2`, ... Each
`make-splits` writes the NEXT one and never touches the previous ones, so
redoing the split (`--repartition`) does not destroy the export's, and a run
can say exactly which one it trained on: the run record stores the version
and its digest, and `compare` shows the version next to every row. Two rows on
different versions are not comparable, and the table makes that visible.

Which version is read: `--split-version vN` on any command, or
`data.split_version` in the config; with neither, the latest.
"""

from __future__ import annotations

import hashlib
import json
import random
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import Enum
from pathlib import Path

from testbank.data.discover import Layout, LayoutMode, Sample, detect_layout

SPLIT_NAMES = ("train", "valid", "test")
MANIFEST_NAME = "manifest.json"
TEST_LOG_PATH = Path("runs") / "test_evaluations.jsonl"

_HEADER = (
    "# Generated by testbank. Frozen split: do not edit by hand.\n"
    "# One identifier per line (file name without extension).\n"
)


class GroupStrategy(str, Enum):
    FILENAME_PREFIX = "filename-prefix"
    DIRECTORY = "directory"
    MANIFEST = "manifest"
    NONE = "none"


class SplitError(RuntimeError):
    """Integrity or usage failure of the splits."""


class SealedTestSetError(SplitError):
    """Test was accessed without explicit authorization."""


@dataclass(frozen=True, slots=True)
class GroupConfig:
    """How samples that must not be spread across splits are grouped.

    `none` declares that every image is independent. It is a statement about
    the world, not a convenient default: if several shots of the same physical
    banknote exist and land in different splits, the metrics come out inflated.
    That is why it requires explicit confirmation.
    """

    strategy: GroupStrategy = GroupStrategy.NONE
    regex: str | None = None
    manifest_path: Path | None = None
    independence_confirmed: bool = False

    def validate(self, *, require_independence_confirmation: bool = True) -> None:
        """`require_independence_confirmation` only applies when CREATING the split.

        In adopt mode the split is already decided by the export: freezing it
        claims nothing about the independence of the samples, so the
        confirmation is not required. The check for groups spread across splits
        is still done whenever there is a group key, because the leak can be
        detected there even if we did not cause it.
        """
        if (
            require_independence_confirmation
            and self.strategy is GroupStrategy.NONE
            and not self.independence_confirmed
        ):
            raise SplitError(
                "--group-key none claims that every image is independent. If "
                "several shots of the same physical banknote are spread across "
                "splits, the metrics come out inflated. Pass "
                "--i-confirm-independence to record that this is a decision and "
                "not an oversight"
            )
        if self.strategy is GroupStrategy.FILENAME_PREFIX and not self.regex:
            raise SplitError(
                "--group-key filename-prefix needs --group-regex with exactly one "
                "capture group that extracts the key from the file name. No "
                "default separator is guessed: it depends on how the export names "
                "the shots of the same banknote"
            )
        if self.strategy is GroupStrategy.MANIFEST and not self.manifest_path:
            raise SplitError(
                "--group-key manifest needs --group-manifest with a JSON "
                "{identifier: group_key}"
            )

    def resolver(self, *, require_independence_confirmation: bool = True) -> GroupResolver:
        self.validate(
            require_independence_confirmation=require_independence_confirmation
        )
        return GroupResolver(self)


class GroupResolver:
    def __init__(self, config: GroupConfig) -> None:
        self.config = config
        self._pattern = re.compile(config.regex) if config.regex else None
        self._table: dict[str, str] = {}
        if config.manifest_path is not None:
            raw = json.loads(Path(config.manifest_path).read_text(encoding="utf-8"))
            if not isinstance(raw, dict):
                raise SplitError(
                    f"{config.manifest_path}: expected a JSON object "
                    "{identifier: group_key}"
                )
            self._table = {str(k): str(v) for k, v in raw.items()}

    def key(self, sample: Sample) -> str:
        strategy = self.config.strategy
        if strategy is GroupStrategy.NONE:
            return sample.sample_id
        if strategy is GroupStrategy.DIRECTORY:
            return sample.directory_key
        if strategy is GroupStrategy.MANIFEST:
            try:
                return self._table[sample.sample_id]
            except KeyError:
                raise SplitError(
                    f"sample '{sample.sample_id}' does not appear in the group "
                    f"manifest {self.config.manifest_path}"
                ) from None
        assert self._pattern is not None
        match = self._pattern.search(sample.sample_id)
        if match is None or not match.groups():
            raise SplitError(
                f"group regex {self.config.regex!r} captures nothing in "
                f"'{sample.sample_id}'"
            )
        return match.group(1)


# -- writing ----------------------------------------------------------------


def _write_split_file(path: Path, ids: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_HEADER + "".join(f"{i}\n" for i in ids), encoding="utf-8")


def _read_split_file(path: Path) -> list[str]:
    if not path.is_file():
        return []
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.append(line)
    return out


def _digest(ids_by_split: dict[str, list[str]]) -> str:
    payload = json.dumps(ids_by_split, sort_keys=True).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


_VERSION = re.compile(r"^v(\d+)$")


def list_versions(splits_dir: str | Path) -> list[str]:
    """Existing versions, oldest to newest (`v1`, `v2`, ...). Numeric order,
    not lexicographic: `v10` goes after `v9`."""
    splits_dir = Path(splits_dir)
    if not splits_dir.is_dir():
        return []
    found = []
    for child in splits_dir.iterdir():
        match = _VERSION.match(child.name)
        if match and child.is_dir() and (child / MANIFEST_NAME).is_file():
            found.append((int(match.group(1)), child.name))
    return [name for _, name in sorted(found)]


def next_version(splits_dir: str | Path) -> str:
    versions = list_versions(splits_dir)
    if not versions:
        return "v1"
    return f"v{int(_VERSION.match(versions[-1]).group(1)) + 1}"


def resolve_version(splits_dir: str | Path, version: str | None = None) -> Path:
    """Directory of `version`, or of the latest one when `version` is None.

    Explicit and loud when it does not exist: silently falling back to
    another version would train on a split other than the one asked for.
    """
    splits_dir = Path(splits_dir)
    versions = list_versions(splits_dir)
    if not versions:
        raise SplitError(
            f"no materialized split in {splits_dir}. Run `testbank make-splits` first"
        )
    if version is None:
        return splits_dir / versions[-1]
    if version not in versions:
        raise SplitError(
            f"split version {version!r} does not exist in {splits_dir}; "
            f"available: {versions}"
        )
    return splits_dir / version


def materialize_splits(
    data_root: str | Path,
    splits_dir: str | Path,
    *,
    groups: GroupConfig | None = None,
    ratios: tuple[float, float, float] = (0.7, 0.15, 0.15),
    seed: int = 20260910,
    overwrite: bool = False,
    repartition: bool = False,
    stratify_regex: str | None = None,
    version: str | None = None,
) -> dict:
    """Materialize the split in adopt or create mode, depending on what is on disk.

    Writes a NEW version under `splits_dir` (`v1`, `v2`, ...; `version` to
    name it explicitly) and never touches the existing ones. `overwrite` only
    allows rewriting the target version itself, which exists for redoing one
    that went wrong; it is not a way to replace an older version.

    Adopt mode: the export's split IS the split. It is neither recomputed nor
    "improved"; it is only frozen into files.

    `repartition` is the explicit exception to that, which is why it is a flag
    and not a behaviour: it ignores the export's split, pools every sample and
    splits as in create mode. It exists because the Roboflow split has 42
    near-duplicate pairs crossing splits (27 measured in color) and a fifth of
    the test set contaminated. The manifest records it as `mode: repartition`,
    with the export's mode beside it, so nobody mistakes this split for the
    original.

    `stratify_regex` splits by stratum (banknote type, taken from the name):
    every split receives its share of every type. See `Stratifier`.
    """
    data_root = Path(data_root)
    container = Path(splits_dir)
    group_config = groups or GroupConfig()

    if version is not None and not _VERSION.match(version):
        raise SplitError(f"a split version is named vN (v1, v2, ...), not {version!r}")
    version = version or next_version(container)
    splits_dir = container / version
    existing = [splits_dir / f"{name}.txt" for name in SPLIT_NAMES]
    if any(p.exists() for p in existing) and not overwrite:
        raise SplitError(
            f"split version {version} is already materialized in {container}. "
            "Versions are immutable: leave out --split-version to write the "
            "next one, or --overwrite to redo this one (it invalidates every "
            "run that used it)"
        )
    splits_dir.mkdir(parents=True, exist_ok=True)

    layout = detect_layout(data_root)
    we_decide = layout.mode is LayoutMode.CREATE or repartition
    if stratify_regex and not we_decide:
        raise SplitError(
            "--stratify-regex only makes sense when we are the ones splitting. "
            "In adopt mode the export decides the split; add --repartition if "
            "you really want to redo it"
        )
    stratifier = Stratifier(stratify_regex) if stratify_regex else None
    # The independence confirmation is only required when we decide the split.
    resolver = group_config.resolver(require_independence_confirmation=we_decide)

    split_notes: list[str] = []
    if we_decide:
        assignment = _random_assignment(
            layout.all_samples,
            resolver,
            ratios=ratios,
            seed=seed,
            stratifier=stratifier,
            warnings_out=split_notes,
        )
    else:
        assignment = {
            name: sorted(s.sample_id for s in layout.groups.get(name, ()))
            for name in SPLIT_NAMES
        }

    _check_disjoint(assignment)
    _check_groups_disjoint(assignment, layout, resolver)

    for name in SPLIT_NAMES:
        _write_split_file(splits_dir / f"{name}.txt", assignment[name])

    strata_counts = None
    if stratifier is not None:
        by_id = {smp.sample_id: smp for smp in layout.all_samples}
        strata_counts = {}
        for name in SPLIT_NAMES:
            for sid in assignment[name]:
                stratum = stratifier.key(by_id[sid])
                strata_counts.setdefault(stratum, {n: 0 for n in SPLIT_NAMES})
                strata_counts[stratum][name] += 1

    repartitioned = repartition and layout.mode is LayoutMode.ADOPT
    manifest = {
        "version": version,
        "created_utc": _now(),
        # `repartition` is a mode of its own in the manifest: whoever reads it
        # has to see at a glance that THIS split is not the export's.
        "mode": "repartition" if repartitioned else layout.mode.value,
        "export_mode": layout.mode.value,
        "data_root": str(data_root.resolve()),
        "seed": seed,
        "ratios": dict(zip(SPLIT_NAMES, ratios)) if we_decide else None,
        "stratify_regex": stratify_regex,
        "strata": strata_counts,
        "group_strategy": group_config.strategy.value,
        "group_regex": group_config.regex,
        "group_manifest": str(group_config.manifest_path)
        if group_config.manifest_path
        else None,
        "independence_confirmed": group_config.independence_confirmed,
        "counts": {name: len(assignment[name]) for name in SPLIT_NAMES},
        "digest": _digest(assignment),
        "notes": list(layout.notes) + split_notes,
        "history": [{"action": "materialize", "utc": _now()}],
    }
    (splits_dir / MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return manifest


class Stratifier:
    """Stratum of each sample: one capture group of a regex over its id.

    In this dataset the denomination only exists in the file name
    (`005_Euro_004_...`, `Multiple_Euro_154_...`): the annotation has a single
    class. So stratifying by banknote type is, literally, a regex over the
    name. It is made explicit instead of hard-coding Roboflow's so that an
    export with another convention does not silently stratify by something
    it is not.
    """

    def __init__(self, regex: str) -> None:
        self.regex = regex
        self._pattern = re.compile(regex)
        if self._pattern.groups != 1:
            raise SplitError(
                "--stratify-regex needs exactly one capture group, which is the "
                f"stratum; {regex!r} has {self._pattern.groups}"
            )

    def key(self, sample: Sample) -> str:
        match = self._pattern.search(sample.sample_id)
        if match is None:
            raise SplitError(
                f"{sample.sample_id}: does not match --stratify-regex {self.regex!r}. "
                "A sample without a stratum cannot be split representatively, "
                "and skipping it silently would leave the split lame without "
                "anyone knowing"
            )
        return match.group(1)


def _split_keys(keys: list[str], ratios, rng) -> dict[str, list[str]]:
    """Split a list of keys into train/valid/test, shuffling with `rng`."""
    keys = sorted(keys)
    rng.shuffle(keys)
    total = len(keys)
    n_train = min(round(total * ratios[0]), total)
    n_valid = min(round(total * ratios[1]), total - n_train)
    return {
        "train": keys[:n_train],
        "valid": keys[n_train : n_train + n_valid],
        "test": keys[n_train + n_valid :],
    }


def _random_assignment(
    samples: tuple[Sample, ...],
    resolver: GroupResolver,
    *,
    ratios: tuple[float, float, float],
    seed: int,
    stratifier: Stratifier | None = None,
    warnings_out: list[str] | None = None,
) -> dict[str, list[str]]:
    """Random assignment by group, with a fixed seed and optional strata.

    GROUPS are split, not files: with `none` every file is its own group and
    the result is the random per-file split. With a near-duplicate manifest,
    the two shots of the same photo land together.

    With strata, the split is done WITHIN each stratum and then merged: every
    split receives its share of every banknote type. A group's stratum is that
    of its first member (in id order).

    If a group crosses strata -- two "nearly identical" photos of banknotes of
    different value -- it is WARNED about and split anyway; it does not stop.
    The first version stopped, and thanks to that it came to light that the
    grayscale duplicate detector confused framing with content (see
    `duplicates.py`). With that fixed, the remaining crossings are one or two,
    and for splitting, one extra group is cheap: two photos go together
    without need, and that is all. Blocking the whole split for that would be
    worse than the problem. The warnings go to the manifest.
    """
    if abs(sum(ratios) - 1.0) > 1e-9:
        raise SplitError(f"ratios must sum to 1, they sum to {sum(ratios)}")
    warnings_out = warnings_out if warnings_out is not None else []

    by_group: dict[str, list[str]] = {}
    stratum_of_group: dict[str, str] = {}
    crossing: dict[str, set[str]] = {}
    for sample in sorted(samples, key=lambda s: s.sample_id):
        key = resolver.key(sample)
        by_group.setdefault(key, []).append(sample.sample_id)
        if stratifier is not None:
            stratum = stratifier.key(sample)
            previous = stratum_of_group.setdefault(key, stratum)
            if previous != stratum:
                crossing.setdefault(key, {previous}).add(stratum)
    if crossing:
        warnings_out.extend(
            f"group {key!r} crosses strata {sorted(strata)}: two photos "
            "considered the same shot with different banknote types. Split as "
            f"{stratum_of_group[key]!r}; worth a look"
            for key, strata in sorted(crossing.items())
        )

    rng = random.Random(seed)
    if stratifier is None:
        chunks = _split_keys(list(by_group), ratios, rng)
    else:
        chunks = {name: [] for name in SPLIT_NAMES}
        by_stratum: dict[str, list[str]] = {}
        for key, stratum in stratum_of_group.items():
            by_stratum.setdefault(stratum, []).append(key)
        # Strata in a fixed order: the seed is only reproducible if the order
        # in which the generator is consumed is too.
        for stratum in sorted(by_stratum):
            for name, keys in _split_keys(by_stratum[stratum], ratios, rng).items():
                chunks[name].extend(keys)

    return {
        name: sorted(sid for key in chunk for sid in by_group[key])
        for name, chunk in chunks.items()
    }


def _check_disjoint(assignment: dict[str, list[str]]) -> None:
    seen: dict[str, str] = {}
    clashes: list[str] = []
    for name in SPLIT_NAMES:
        for sample_id in assignment[name]:
            if sample_id in seen:
                clashes.append(f"'{sample_id}' is in '{seen[sample_id]}' and in '{name}'")
            else:
                seen[sample_id] = name
    if clashes:
        raise SplitError(
            "a sample cannot be in two splits:\n  "
            + "\n  ".join(clashes[:20])
            + (f"\n  ... and {len(clashes) - 20} more" if len(clashes) > 20 else "")
        )


def _check_groups_disjoint(
    assignment: dict[str, list[str]], layout: Layout, resolver: GroupResolver
) -> None:
    if resolver.config.strategy is GroupStrategy.NONE:
        return
    by_id = {s.sample_id: s for s in layout.all_samples}
    group_split: dict[str, str] = {}
    clashes: list[str] = []
    for name in SPLIT_NAMES:
        for sample_id in assignment[name]:
            sample = by_id.get(sample_id)
            if sample is None:
                continue
            key = resolver.key(sample)
            previous = group_split.get(key)
            if previous is None:
                group_split[key] = name
            elif previous != name:
                clashes.append(
                    f"group '{key}' appears in '{previous}' and in '{name}' "
                    f"(e.g. '{sample_id}')"
                )
    if clashes:
        raise SplitError(
            "a group cannot be spread across splits:\n  "
            + "\n  ".join(sorted(set(clashes))[:20])
            + "\n  In adopt mode this means the EXPORT already came with the "
            "leak. It is not fixed silently: --repartition redoes the split by "
            "groups and records it in the manifest"
        )


# -- reading ----------------------------------------------------------------


class SplitLoader:
    """Read-only access to the frozen split.

    Checks integrity on load. Test stays sealed: `load("test")` requires
    allow_test=True and the experiment runner never passes it.
    """

    def __init__(
        self,
        splits_dir: str | Path,
        data_root: str | Path | None = None,
        *,
        version: str | None = None,
    ):
        """`splits_dir` is the container of versions; `version` picks one
        (`None` = the latest). `self.version` says which one was resolved, so
        a run can record it instead of the ambiguous "latest"."""
        self.splits_dir = resolve_version(splits_dir, version)
        self.version = self.splits_dir.name
        manifest_path = self.splits_dir / MANIFEST_NAME
        self.manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        self.data_root = Path(data_root or self.manifest["data_root"])
        self._assignment = {
            name: _read_split_file(self.splits_dir / f"{name}.txt")
            for name in SPLIT_NAMES
        }
        self._layout = detect_layout(self.data_root)
        self._by_id = {s.sample_id: s for s in self._layout.all_samples}
        self._verify()

    def _verify(self) -> None:
        _check_disjoint(self._assignment)
        strategy = GroupStrategy(self.manifest["group_strategy"])
        if strategy is not GroupStrategy.NONE:
            config = GroupConfig(
                strategy=strategy,
                regex=self.manifest.get("group_regex"),
                manifest_path=(
                    Path(self.manifest["group_manifest"])
                    if self.manifest.get("group_manifest")
                    else None
                ),
                independence_confirmed=True,
            )
            _check_groups_disjoint(
                self._assignment,
                self._layout,
                config.resolver(require_independence_confirmation=False),
            )

        listed = {sid for ids in self._assignment.values() for sid in ids}
        missing = sorted(listed - set(self._by_id))
        if missing:
            raise SplitError(
                f"{len(missing)} samples of the split are not in "
                f"{self.data_root}: {missing[:10]}"
                + (" ..." if len(missing) > 10 else "")
                + ". The split is frozen; if the data directory changed, fix "
                "the directory, not the split"
            )

    def unassigned(self) -> tuple[str, ...]:
        listed = {sid for ids in self._assignment.values() for sid in ids}
        return tuple(sorted(set(self._by_id) - listed))

    def load(self, split: str, *, allow_test: bool = False) -> tuple[Sample, ...]:
        if split not in SPLIT_NAMES:
            raise SplitError(f"unknown split '{split}'; valid: {SPLIT_NAMES}")
        if split == "test" and not allow_test:
            raise SealedTestSetError(
                "test is sealed. The experiment runner cannot read it: looking "
                "at test during development turns it into a second validation "
                "set. Use the `evaluate-test` command, which records every "
                "access in runs/test_evaluations.jsonl"
            )
        return tuple(self._by_id[sid] for sid in self._assignment[split])

    def ids(self, split: str) -> tuple[str, ...]:
        return tuple(self._assignment[split])

    def describe(self) -> dict:
        """What a run records about the split it used: enough to know whether
        two runs are comparable without opening the split files."""
        return {
            "version": self.version,
            "mode": self.manifest.get("mode"),
            "digest": self.manifest.get("digest"),
            "counts": dict(self.manifest.get("counts", {})),
        }


# -- the sealed test set ----------------------------------------------------


def read_test_accesses(log_path: Path | None = None) -> list[dict]:
    """Previous accesses to the sealed set, oldest to newest.

    Read BEFORE evaluating, and shown. The seal does not prevent looking at
    test: it prevents looking at it without a record. Seeing the count up
    front is what makes the record worth anything.
    """
    path = Path(log_path or TEST_LOG_PATH)
    if not path.exists():
        return []
    entries: list[dict] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entries.append(json.loads(line))
        except json.JSONDecodeError:
            # A corrupt line cannot hide the others: the access count is
            # precisely what must not be losable.
            entries.append({"utc": "?", "run": "?", "reason": "[unreadable line]"})
    return entries


def record_test_access(
    reason: str,
    run_name: str,
    log_path: Path | None = None,
    **details,
) -> dict:
    """Record every access to the sealed set.

    `details` stores WHAT was evaluated -- commit, weights, metric obtained --
    not only when. A log that only says "someone looked at test on Tuesday"
    is useless for the only thing that matters: knowing whether the final
    number was picked among several.
    """
    path = Path(log_path or TEST_LOG_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    entry = {"utc": _now(), "run": run_name, "reason": reason, **details}
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(entry, ensure_ascii=False) + "\n")
    return entry
